kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pwgen
subjects:
- kind: ServiceAccount
  name: pwgen
  namespace: pwgen
roleRef:
  kind: ClusterRole
  name: pwgen
  apiGroup: rbac.authorization.k8s.io
