version: 2.1

orbs:
  slack: circleci/slack@3.4.2
  docker: circleci/docker@1.3.0

jobs:
  build-and-push:
    executor: docker/docker
    environment:
      REGISTRY_HOST: harbor.k8s.libraries.psu.edu
      REGISTRY_URL: library/pwgen-operator
      DOCKER_LOGIN: 'robot$circleci'
    steps:
    - setup_remote_docker
    - checkout
    - docker/check:
        registry: $REGISTRY_HOST
    - docker/build:
        image: $REGISTRY_URL
        registry: $REGISTRY_HOST
        tag: $CIRCLE_SHA1
    - docker/push:
        image: $REGISTRY_URL
        registry: $REGISTRY_HOST
        tag: $CIRCLE_SHA1

workflows:
  docker_push:
    jobs:
      - build-and-push:
          filters:
            branches:
              only:
                - master
