 apiVersion: apiextensions.k8s.io/v1beta1
 kind: CustomResourceDefinition
 metadata:
   name: pwgens.edu.psu.libraries
 spec:
   scope: Namespaced
   group: edu.psu.libraries
   validation:
     openAPIV3Schema:
       properties:
         spec:
           type: object
           properties:
             secret_items:
               type: array
               items:
                 type: object
                 properties:
                   key:
                     description: The Key within the created secret
                     example: MYSQL_ROOT_PASSWORD
                     type: string
                   length:
                     type: integer
                     description: If specified, generate a secret of this length
                     example: 20
                   value:
                     descripton: String value of the secret. If omitted the controller will generate a random string. Use this to force a value.
                     example: s3curep4ssw0rd
                     type: string
                 required:
                   - key  
   versions:
     - name: v1alpha1
       served: true
       storage: true
       schema:
   names:
     kind: PwGen
     plural: pwgens
     singular: pwgen
     shortNames:
       - pwgs
       - pwg