name: Build

on: [push]

jobs:
  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
    - name: Docker build
      run: |
        docker build -t harbor.dsrd.libraries.psu.edu/library/pwgen-operator:$GITHUB_SHA . 
        docker push harbor.dsrd.libraries.psu.edu/library/pwgen-operator:$GITHUB_SHA
